spring:
     mvc:
          hiddenmethod:
               filter:
                    enabled: true
     application:
          name: docker
     jpa:
          hibernate:
               ddl-auto: update
     datasource:
          url: jdbc:mysql://localhost:3306/auth
          password: Edomews
          username: Edomew
server:
     port: 8080
